### ISSUE TITLE
Deadline zondag 25 juni

### ISSUE THREAD

**Issue by HermansAnthony** [Stride-Apollo/Stride#51]
- [ ] Algemeen 
  - [ ] Verslag 
  - [ ] Manual
  - [ ] Performance report
  - [ ] Mail
  - [ ] Website update
  - [ ] Optioneel: Data over prototypes
- [ ] Code
  - [ ] MPI
  - [ ] Visualisatie
  - [ ] Merge
  - [ ] HDF5 fix
  - [ ] Output aanpassen (zie Slack)
  - [ ] Configuratie

**Comment by evertheylen** [comment]
zie https://github.com/Stride-Apollo/Stride/projects/1
